const movies = [
  { id: 1, title: "The Departed", image: "https://image.tmdb.org/t/p/w500/49B1gF3Yy4vJ4y23mV1T0Z3JeD4.jpg" },
  { id: 2, title: "The Godfather", image: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg" },
  { id: 3, title: "Lupin III: Cagliostro no Shiro", image: "https://image.tmdb.org/t/p/w500/5jGkyo0MAb5Hj8HwtiwMaAzdV7R.jpg" },
  { id: 4, title: "Psycho", image: "https://image.tmdb.org/t/p/w500/81d8zVld3NL.jpg" },
  { id: 5, title: "Rocky", image: "https://image.tmdb.org/t/p/w500/6zyM5xtPJl2JcgVy5VR3YG1W4yS.jpg" },
  { id: 6, title: "The End of Evangelion", image: "https://image.tmdb.org/t/p/w500/79OJTXy30vB6ClGoaU17eRUhClq.jpg" },
  { id: 7, title: "Goodfellas", image: "https://image.tmdb.org/t/p/w500/1hYTx5aQ0dbZ4FgWCf31AzQ0GPR.jpg" },
  { id: 8, title: "9 Reinas", image: "https://image.tmdb.org/t/p/w500/hOB5qiPCwwGL4QUsuduRttsmvtI.jpg" },
  { id: 9, title: "The Shawshank Redemption", image: "https://image.tmdb.org/t/p/w500/5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg" },
  { id: 10, title: "Rear Window", image: "https://image.tmdb.org/t/p/w500/7IvanENKcFMy3ZykGPlkKjgIjh.jpg" },
  { id: 11, title: "Urusei Yatsura: Beautiful Dreamer", image: "https://image.tmdb.org/t/p/w500/58YClYpJzGV1Y2s1bopIrLf3vsp.jpg" },
  { id: 12, title: "Casino", image: "https://image.tmdb.org/t/p/w500/64oZUpbT2DxbnSdlcGkdRc1loPQ.jpg" },
  { id: 13, title: "North by Northwest", image: "https://image.tmdb.org/t/p/w500/7Ivxq1bqjOc9LBhwalWRtjJ7o2M.jpg" },
  { id: 14, title: "Raging Bull", image: "https://image.tmdb.org/t/p/w500/6WkfGihqTFUUsMdNDQn6iAfvNfh.jpg" },
  { id: 15, title: "The Godfather Part II", image: "https://image.tmdb.org/t/p/w500/amVTEi2u19riI5bxFiilIfZeh1W.jpg" },
  { id: 16, title: "The Ideon: Be Invoked", image: "https://image.tmdb.org/t/p/w500/placeholder.jpg" },
  { id: 17, title: "The Departed", image: "https://image.tmdb.org/t/p/w500/nmmQXQfAVlwHab47ESAeabYtpdk.jpg" },
  { id: 18, title: "Spider-Man", image: "https://image.tmdb.org/t/p/w500/lHZ68epONbOR6lv81G4GYG8uzHb.jpg" },
  { id: 19, title: "Spider-Man 2", image: "https://image.tmdb.org/t/p/w500/1sISI0yYT0amub3spEPr1viOa8Y.jpg" },
  { id: 20, title: "Sonic the Hedgehog 3", image: "https://image.tmdb.org/t/p/w500/placeholder2.jpg" }
];